<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="Prelude.fs" />
    <Compile Include="Noise.fs" />
    <Compile Include="Domain.fs" />
    <Compile Include="Tuning.fs" />
    <Compile Include="ProcGen/AudioSynth.fs" />
    <Compile Include="Bepu.fs" />
    <Compile Include="Soil/Volume.fs" />
    <Compile Include="Soil/Carve.fs" />
    <Compile Include="Soil/Settle.fs" />
    <Compile Include="Soil/Particles.fs" />
    <Compile Include="Soil/Collision.fs" />
    <Compile Include="Soil/Api.fs" />
    <Compile Include="Excavator/Linkage.fs" />
    <Compile Include="Excavator/Fee.fs" />
    <Compile Include="Excavator/Hydraulics.fs" />
    <Compile Include="Physics.fs" />
    <Compile Include="Excavator/Machine.fs" />
    <Compile Include="Sim.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BepuPhysics" Version="2.5.0-beta.29" />
  </ItemGroup>
</Project>
